#debug or release
run_mode = "debug"

[db]
type = "mysql"
#host = "192.168.0.146:3306"  # ubuntu
#host = "127.0.0.1:3306"  # 本地
#host = "172.17.0.1:3306"  # docker
host = "39.97.212.82:3306" # 服务器

user = "root"
password = "fsw.1996"
database = "harbor"
tablePrefix = "harbor_"

[app]
page_size = 5
jwt_secret = "23347$040412"

[server]
http_port = 8000
read_timeout = 60
write_timeout = 60